### ISSUE TITLE
Partials and pages without meta data whose first line begins with a doT expression will not compile

### ISSUE THREAD

**Issue by elisehein** [cambridge-healthcare/grunt-stencil#1]
This is because the check to see whether the file has meta data is a simple `src[0] === '{'`. This should exclude files that begin with `{{`.

**Comment by szymonrw** [comment]
It's fixed in tdd branch.

**Comment by elisehein** [comment]
Not fixed in master.

**Comment by szymonrw** [comment]
Fixed in 1.0.0
