### ISSUE TITLE
Documentation unclear with option meta_data_separator

### ISSUE THREAD

**Issue by crwang** [cambridge-healthcare/grunt-stencil#10]
I spent a couple hours trying to get this to work (on Windows) and was about to give up until I saw the meta_data_separator and was able to add in "\r\n\r\n" to get it to work in Windows.

I wonder somehow this option can be discarded since it'll cause a lot of cross-platform issues.  I'd like to use grunt-stencil for some of our work but I'd like it work on both Windows and Mac/Linux.

Could an array work for that parameters so I could use:

meta_data_separator: ["\r\n\r\n", "\n\n"] so it's cross-platform compatible?

**Comment by szymonrw** [comment]
Hi :)

Because it looked like a quick fix, I've just did it. Should be published today. See #11 .

**Comment by szymonrw** [comment]
Published on npm. Please make sure you've upgraded to 1.0.2. Let us know if it fixes that for you.

**Comment by crwang** [comment]
Awesome!  I upgraded and it works great for me, in that I can now remove that setting and not worry about it anymore.
