### ISSUE TITLE
well formatted html output?

### ISSUE THREAD

**Issue by lhwparis** [cambridge-healthcare/grunt-stencil#13]
hi, first thanks for stencil i like it :)
is there any way to get well formatted html out of stencil? with default settings it just generates a single line html file :(

**Comment by szymonrw** [comment]
Hi :-)

You can put

```
dot_template_settings: { strip: true }
```

in your stencil `options`.

It's no prettifier. It'll just stop doT from compressing whitespace in the output.

**Comment by lhwparis** [comment]
thank you very much works wenn and now i can use it with grunt-usemin :)
