### ISSUE TITLE
Collapsed HTML

### ISSUE THREAD

**Issue by bubbleheadinc** [cambridge-healthcare/grunt-stencil#15]
Stencil has made my day. One thing though...Is there a way to preserve the HTML indentation structure? When it generates the output file it collapses/minifies the HTML, but I need the markup to be formatted.

Thanks much.

**Comment by szymonrw** [comment]
It's nice to hear that :-)

I think solution to your problem is the same as in #13

**Comment by bubbleheadinc** [comment]
Ah yes! I guess I should have searched better :) 

I set the config to false and it works...Not very pretty, but gets the job done. I'll take a look at grunt-prettify too.

```
dot_template_settings: { strip: false }
```

Thank you!

**Comment by szymonrw** [comment]
Cool!
