### ISSUE TITLE
make partital file format configurable

### ISSUE THREAD

**Issue by lhwparis** [cambridge-healthcare/grunt-stencil#17]
at the moment all files for the dot.js parser has to end with .dot.html. plsease make this configurable so we can set dot.js templates to file ending .123 for example

**Comment by szymonrw** [comment]
How about allowing templates and partials to have any arbitrary extensions? (It would still need to have `.dot` somewhere in the name to be processed by doT parser)

Then names like `asdf.dot.qwer` and `zcxv.dot.123` would work.

**Comment by lhwparis** [comment]
no my favorite is to have the possability to configure it because i dont want to have the .dot in my partitial names. i prefer to use just .html for dot partitials and .md for markdown.

**Comment by szymonrw** [comment]
Stencil determines which "compilers" (markdown, doT) to process the file with from it's file name. So if a file has `.md` or `.dot` as one of it's extensions, it'll be processed by markdown or doT, respectively.

If you look at the [`applies_to` method](https://github.com/cambridge-healthcare/grunt-stencil/blob/f49d7180faa2eccb8508ef1d0e38d2d48f5ca754/lib/dot_compiler.js#L31-33) from the `dot_compiler.js` it actually depends on the compiler plugin implementation and can be any reasonable condition.

It works like this on purpose: we can plug in more compilers than just doT and markdown in the future (like handlebars or jade). Right now those plugins are in the same project and cannot be easily added/removed/configured.

I think what should be the ultimate solution is to extract compiler plugins from stencil core. Then you could override the `applies_to` method of the compiler plugin to your liking or write your own plugin. (As you can see from the [`dot_compiler.js`](https://github.com/cambridge-healthcare/grunt-stencil/blob/f49d7180faa2eccb8508ef1d0e38d2d48f5ca754/lib/dot_compiler.js) it's just a thin wrapper.)

This might be a good direction for 2.0.

**Comment by lhwparis** [comment]
i agree with you but even when i decide to not name it .dot.html but .d.html i cant do that at the moment and make it configurable is the easiest way. what i want to do is dot.js is default compiler for html files so ALL html files are dot.js templates and all markdown files are named: .md. i cant see why this should not work and why i need a *.dot syntax in this case.

**Comment by szymonrw** [comment]
You're right. It makes little sense to have `.dot.` everywhere and it makes a lot of sense to do what you've proposed. That could be a default behaviour in some following 1.x release.

Do you still need to be able to configure the extensions or is having `.html` for doT.js files enough for you?

_off-topic:_ I've [sketched out some ideas for 2.0](https://github.com/cambridge-healthcare/grunt-stencil/blob/master/2.0.md), where all compilers will be provided by plugins (so the user can use for example handlebars instead of doT). We'll need some way to tell when they apply to a certain file and I wonder if there's any better way than with file extensions.

**Comment by lhwparis** [comment]
.html => dot.js compiler does the job for me at the moment :)

other options for 2.0:
1. add a json header like in dot.js templates in each file and define the engine to use in there.
2. make it possible to configure special folders + subfolders for each compiler like all files in /documentation/\* are markdown files

**Comment by szymonrw** [comment]
Hey, as of 1.1.0 all HTML files are now processed with doT :)

**Comment by lhwparis** [comment]
many thanks for that!
