### ISSUE TITLE
How to access meta-data from parent with partials

### ISSUE THREAD

**Issue by tommica** [cambridge-healthcare/grunt-stencil#6]
Okay, I'm doing something wrong when I'm trying to access the meta-data of the "main.dot.html" from the partial "product.dot.html"

**main.dot.html**

```
{
    "pTitle": "iddqd"
}

<div class="products">
    {{= it.include('partials/product.dot.html') }}
</div>
```

**product.dot.html**

```
<h1>{{= it.pTitle }}</h1>
```

**Output**

```
<div class="products">
    <h1>undefined</h1>
</div>
```

**Comment by szymonrw** [comment]
To access data from including file you have to pass it explicitly to the partial, like this:

```
{{= it.include("partials/product.dot.html", { pTitle: it.pTitle }) }}
```

Hope this helps. Please let me know if that works for you.

Our documentation lacks an example for this. I'll update it soon.

**Comment by tommica** [comment]
Yes, this works - Thanks!
